// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerification struct {
	ID        string
	Token     string
	UserID    string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type RefreshToken struct {
	ID        string
	Token     string
	UserID    string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type ResetToken struct {
	ID        string
	Token     string
	UserID    string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type User struct {
	ID            string
	Name          string
	Email         string
	Password      string
	Subdomain     string
	EmailVerified bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
