// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reset_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResetToken = `-- name: CreateResetToken :one
insert into reset_tokens (id, token, user_id, created_at, expires_at)
values ($1, $2, $3, $4, $5) returning id, token, user_id, created_at, expires_at
`

type CreateResetTokenParams struct {
	ID        string
	Token     string
	UserID    string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (ResetToken, error) {
	row := q.db.QueryRow(ctx, createResetToken,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ResetToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAllResetTokens = `-- name: DeleteAllResetTokens :exec
delete from reset_tokens where user_id = $1
`

func (q *Queries) DeleteAllResetTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAllResetTokens, userID)
	return err
}

const getResetTokenByToken = `-- name: GetResetTokenByToken :one
select id, token, user_id, created_at, expires_at from reset_tokens where token = $1
`

func (q *Queries) GetResetTokenByToken(ctx context.Context, token string) (ResetToken, error) {
	row := q.db.QueryRow(ctx, getResetTokenByToken, token)
	var i ResetToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
