import type { Metadata } from "next";
import {UserNav} from "@/components/user-nav";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function UserLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="mx-3">
            <UserNav subdomain="link" />
            {children}
        </div>
    );
}
