import type { Metadata } from "next";
import {MainNav} from "@/components/main-nav";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <MainNav />
            {children}
        </>
    );
}
